networks:
  b2b_network:
    driver: bridge
  traefik-net:
    external: true

services:
  frontend:
    build: .
    image: techchaide/mantenimiento-predictivo-frontend:1.0
    container_name: mantenimiento_predictivo_frontend_prod
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_BASE_PATH=/Mantenimiento-Predictivo
      - HOSTNAME=0.0.0.0
    networks:
      - b2b_network
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.mantenimiento-predictivo-frontend-prod.rule=Host(`apps.chaide.com`) && (PathPrefix(`/Mantenimiento-Predictivo`) || PathPrefix(`/_next`) || PathPrefix(`/favicon.ico`))"
      - "traefik.http.routers.mantenimiento-predictivo-frontend-prod.entrypoints=websecure"
      - "traefik.http.routers.mantenimiento-predictivo-frontend-prod.priority=100"
      # Note: No stripPrefix middleware for frontend so the app receives the /b2b prefix.
      - "traefik.http.routers.mantenimiento-predictivo-frontend-prod.tls=true"
      - "traefik.http.services.mantenimiento-predictivo-frontend-prod.loadbalancer.server.port=3000"

      # --- MIDDLEWARES ---
      # 1. Stripprefix para eliminar /Mantenimiento-Predictivo antes de llegar a Next.js
      - "traefik.http.middlewares.strip-mantenimiento.stripprefix.prefixes=/Mantenimiento-Predictivo"

      # 2. Define el middleware de la lista blanca de IPs
      - "traefik.http.middlewares.lista-ips-mantenimiento-predictivo.ipwhitelist.sourceRange=127.0.0.1/32, 201.234.212.234/32"

      # 3. Aplica ambos middlewares al router del frontend
      - "traefik.http.routers.mantenimiento-predictivo-frontend-prod.middlewares=strip-mantenimiento, lista-ips-mantenimiento-predictivo"